services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"

  db:
    image: neo4j:5.26.0
    environment:
      - NEO4J_AUTH=neo4j/12345678 
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:7474/", "||", "exit 1"]
      interval: 0.5s
      retries: 30

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
      - ./minio/certs:/certs
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: miniotest
      MINIO_SECRET_KEY: miniotest
      MINIO_SCHEME: https
      SSL_CERT_FILE: /certs/public.crt
    command: server --console-address ":9001" /data --certs-dir /certs

  producer:
    build:
      dockerfile: Dockerfile
      context: .
    command: python3 src/app.py
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - db
      - redis
      - minio
    stop_signal: SIGINT

  consumer:
    build:
      dockerfile: Dockerfile
      context: .
    command: python3 consumer
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - db
      - redis
      - minio
    stop_signal: SIGINT
