version: '0.3'

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"
  
  db:
    image: postgres:16.5
    env_file: config/.env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER}", "-d", "${PG_DB}" ]
      interval: 0.5s
      retries: 30

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
      - ./minio/certs:/certs
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SCHEME: https
      SSL_CERT_FILE: /certs/public.crt
    command: server --console-address ":9001" /data --certs-dir /certs

# volumes:
#   minio_storage: {}