version: '0.3'

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"
  
  db:
    image: postgres:16.5
    env_file: config/.env
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test", "-d", "postgres" ]
      interval: 0.5s
      retries: 30

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
      - ./minio/certs:/certs
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SCHEME: https
      SSL_CERT_FILE: /certs/public.crt
    command: server --console-address ":9001" /data --certs-dir /certs
  
  producer:
    build:
      dockerfile: Dockerfile
      context: .
    command: python3 src/app.py
    env_file: config/.env
    stop_signal: SIGINT

  consumer:
    build:
      dockerfile: Dockerfile
      context: .
    # TODO: fix sqlalchemy issue
    command: python3 consumer
    env_file: config/.env
    stop_signal: SIGINT

# volumes:
#   minio_storage: {}
