name: SiriusDates
on: [push]
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ruff
    - name: Lint with ruff
      run: |
        ruff check 
        
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      db:
        image: neo4j:5.26.0
        env:
          NEO4J_AUTH: neo4j/12345678 
        ports:
          - "7474:7474"
          - "7687:7687"

    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Dependencies installation
      run: |
        cp config/.env.example config/.env
        python -m pip install --upgrade pip
        pip install pytest
        pip install numpy
        pip install httpx
        pip install poetry
        pip install pytest_asyncio
        pip install -r requirements.txt
        poetry install
    - name: Creating DB indexes
      run: DB_HOST=localhost PYTHONPATH=. python3 scripts/setup_db.py
    - name: Pytest
      run: DB_HOST=localhost PYTHONPATH=. pytest tests/
