name: SiriusDates
on: [push]
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ruff
    - name: Lint with ruff
      run: |
        ruff check 
        
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Dependencies installation
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install numpy
        poetry install
    - name: Pytest
      run: PYTHONPATH=. pytest tests/
